### ISSUE TITLE
php artisan inspect:sniff - Exit Status 0 regardless of the errors

### ISSUE THREAD

**Issue by amcfarlane** [brodkinca/BCA-Laravel-Inspect#1]
I am very new to GitHub (and its etiquette), my apologises if this isn't the right place to post this but I was looking for some help with the exit status of this tool.

Is there a way to have it return an exit status >0 if any errors are found?

**Comment by brodkin** [comment]
That's a fair question... Because this tool is just a wrapper around other OSS it's really hard to say if I can return a status or not. I'll try to look at this sometime soon.

Generally speaking people integrate these tools with other software by returning the reports in a computer-readable format like XML and then that is parsed for error states and such.
