### ISSUE TITLE
PHPMD version up

### ISSUE THREAD

**Issue by hyungsul** [brodkinca/BCA-Laravel-Inspect#5]
I have the issue in php md, which was fixed in PHPMD 2.0.
https://github.com/phpmd/phpmd/issues/143

Is it possible to upgrade the php md version in composer.json?

**Comment by brodkin** [comment]
Sorry for the delay. I took this into consideration but ultimately since phpmd is not a dependency of this project I don't want to attempt to solve the issue here when it needs to be fixed upstream. I'm told that a fix is on its way from the vendor and will release it once available and deemed stable for inclusion.
